# Create this secret with:
# kubectl create secret generic dead-on-film-secrets \
#   --namespace=dead-on-film \
#   --from-literal=TMDB_API_TOKEN=your_token_here
#
# Or apply this file after base64 encoding your token:
# echo -n 'your_token_here' | base64

apiVersion: v1
kind: Secret
metadata:
  name: dead-on-film-secrets
  namespace: dead-on-film
type: Opaque
data:
  TMDB_API_TOKEN: <BASE64_ENCODED_TOKEN>
