apiVersion: v1
kind: Service
metadata:
  name: dead-on-film-api
  namespace: deadonfilm
spec:
  selector:
    app: dead-on-film
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: dead-on-film-frontend
  namespace: deadonfilm
spec:
  selector:
    app: dead-on-film
  ports:
    - name: frontend
      port: 80
      targetPort: 3000
  type: ClusterIP
